### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### Sign Up
# @no-cookie-jar
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "email": "logintest01",
  "password": "1234"
}

### Email Varification
# @no-cookie-jar
POST http://localhost:8080/auth/send-email
Content-Type: application/json

{
  "emailId": "숙명메일아이디"
}

### Email Varification
# @no-cookie-jar
POST http://localhost:8080/auth/verify-code
Content-Type: application/json

{
  "emailId": "숙명메일아이디",
  "code": "인증코드"
}