### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### Sign Up
# @no-cookie-jar
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "email": "logintest01",
  "password": "1234"
}

