### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### 해당 유저 && 해당 챕터에 활성화된 계획 리스트 반환
GET http://localhost:8080/plan/specialist
Content-Type: application/json
Cookie: ACCESS_TOKEN=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ5c2owNTA5IiwiaWF0IjoxNzQyNDQzMTgyLCJleHAiOjE3NDI0NDY3ODJ9.5LXSh6iWhOZCru78IMKn7OtuVe1tveTpsciMF94Hyyw

### 계획 실행
POST http://localhost:8080/plan/execute
Content-Type: application/json
Cookie: ACCESS_TOKEN=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ5c2owNTA5IiwiaWF0IjoxNzQyNDQzMTgyLCJleHAiOjE3NDI0NDY3ODJ9.5LXSh6iWhOZCru78IMKn7OtuVe1tveTpsciMF94Hyyw

[
  { "taskName": "수업" },
  { "taskName": "공부" },
  { "taskName": "외국어" },
  { "taskName": "알바" },
  { "taskName": "동아리" },
  { "taskName": "휴식" },
  { "taskName": "취미" },
  { "taskName": "운동" },
  { "taskName": "약속" },
  { "taskName": "봉사" },
  { "taskName": "여행" },
  { "taskName": "전공학회" },
  { "taskName": "자소서 작성" },
  { "taskName": "학생회" }
]