name: Deploy to EC2

on:
  push:
    branches:
      - ci-cd

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission to gradlew
        run: chmod +x ./noonsongmaker/gradlew

      - name: Build with Gradle (skip test)
        run: ./noonsongmaker/gradlew -p noonsongmaker clean build -x test

      - name: SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: noonsongmaker/build/libs/noonsongmaker-0.0.1-SNAPSHOT.jar
          target: /home/ec2-user/build/libs

      - name: SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          script: |
            cd /home/ec2-user
            docker-compose down
            docker-compose up -d
